apiVersion: v1
kind: ServiceAccount
metadata:
  name: jane
  namespace: dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ken
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: dev
subjects:
  - kind: ServiceAccount # Group, ServiceAccount
    name: jane
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role # явно указываем Role или ClusterRole
  name: admin # а тут имя той Role или ClusterRole к которой мы биндимся
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view
  namespace: dev
subjects:
  - kind: ServiceAccount # Group, ServiceAccount
    name: ken
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role # явно указываем Role или ClusterRole
  name: view # а тут имя той Role или ClusterRole к которой мы биндимся
  apiGroup: rbac.authorization.k8s.io