apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob
  namespace: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods 
subjects:
  - kind: Group # Group, ServiceAccount
    name: system:serviceaccounts:prometheus
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole # явно указываем Role или ClusterRole
  name: pod-reader # а тут имя той Role или ClusterRole к которой мы биндимся
  apiGroup: rbac.authorization.k8s.io